#!/bin/sh
# Copyright (C) 2010-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Schema generator script: RNC.
#
# This schema generator creates a single RNC file from the XML schema using
# an XSL transformation via the tool xsltproc.

xsltproc ./RNC.xsl $1
