#!/bin/sh
#
# OpenVAS
# $Id$
# Description: Mapgenerator for geographically located target systems
#
# This mapgenerator creates a PNG image showing hosts on a worldmap.
# The first step is to create a CSV file from the OMP report using xsltproc.
# Then the file is merged with the file contianing the location information.
# To generate the map, the resulting CSV file is converted into the shape format
# used by MapServer and then drawn to the image file using shp2img.
#
# Authors:
# Raimund Renkert <raimund.renkert@greenbone.net>
# Jan-Oliver Wagner <jan-oliver.wagner@greenbone.net>
#
# Copyright:
# Copyright (C) 2010 Greenbone Networks GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2,
# or, at your option, any later version as published by the Free
# Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

TMP=`mktemp -d` || exit 1
RWD=`pwd | sed -e "s/\//\\\\\\\\\//g"`

# Create csv file from report using xslt.
xsltproc ./report_to_csv_host.xsl $1 | grep -v "^ *$" > ${TMP}/hosts_clean.csv

# Merge locations file and host file
cat locations.csv ${TMP}/hosts_clean.csv | awk -f ./join.awk > \
  ${TMP}/host_locations.csv

# We need the .vrt file where the shapefile is
cp hosts.vrt ${TMP}

# Set the paths
echo  "sed -e \"s/__RWD__/"${RWD}"/g\"" > ${TMP}/do_sed
. ${TMP}/do_sed < world_map.map > ${TMP}/world_map.map

# Create shape file using ogr2ogr.
( cd ${TMP} ; ogr2ogr -f "ESRI Shapefile" . host_locations.csv )
( cd ${TMP} ; ogr2ogr -f "ESRI Shapefile" . hosts.vrt )

# Render image
( cd "${TMP}" ; shp2img -m world_map.map -o "${TMP}/out.png" )

cat "${TMP}/out.png" && rm -rf "${TMP}"

