#!/bin/sh
# Copyright (C) 2010-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Schema generator script: HTML.
#
# This schema generator creates a single HTML file from the XML schema using
# an XSL transformation via the tool xsltproc.

xsltproc ./HTML.xsl $1
