.TH gvm-migrate-to-postgres 8 User Manuals
.SH NAME
gvm-migrate-to-postgres \- Migrate GVM database to Postgres
.SH SYNOPSIS
\fBgvm-migrate-to-postgres OPTIONS
\f1
.SH DESCRIPTION
Migrate Greenbone Vulnerability Manager database from SQLite3 to Postgres. 
.SH OPTIONS
.TP
\fB--version\f1
Print version and exit.
.TP
\fB--help\f1
Print help message and exit.
.TP
\fB--selftest\f1
Perform self-test and exit.
.SH SEE ALSO
\fBgvmd(8)\f1
.SH MORE INFORMATION ABOUT THE OPENVAS PROJECT
The canonical places where you will find more information about the OpenVAS project are: \fBhttp://www.openvas.org/\f1 (Official site) \fBhttp://wald.intevation.org/projects/openvas/\f1 (Development Platform) 
.SH COPYRIGHT
The Greenbone Vulnerability Manager is released under the GNU GPL, version 2, or, at your option, any later version. 
