.TH openvasmd 8 User Manuals
.SH NAME
openvasmd \- Manager daemon of the Open Vulnerability Assessment System (OpenVAS)
.SH SYNOPSIS
\fBopenvasmd OPTIONS
\f1
.SH DESCRIPTION
OpenVAS Scanner, openvassd(8), acts as a service and offers a communication protocol for its clients called OTP. The core task of the OpenVAS Scanner is the actual scan process. 

The OpenVAS Manager is a OTP client and adds various management functionalities to handle and organise scan results. Thus OpenVAS Manager acts as a layer between the OpenVAS Scanner and its own clients (for example omp(8), gsad(8) or gsd(8)) which connect via the OMP protocol to the OpenVAS Manager. 

A related service is OpenVAS Administrator, openvasad(8) which among other tasks also manages user accounts for OpenVAS. 
.SH OPTIONS
.TP
\fB-a, --listen=\fIADDRESS\fB\f1
Listen on ADDRESS.
.TP
\fB-l, --slisten=\fIADDRESS\fB\f1
Connect to server (openvassd) at address ADDRESS.
.TP
\fB--max-email-attachment-size=\fISIZE\fB\f1
Maximum number of bytes permitted in alert email attachments. 

0 to use the default, negative to allow any size. 
.TP
\fB--max-email-include-size=\fISIZE\fB\f1
Maximum number of bytes permitted in reports inlined in alert email attachments. 

0 to use the default, negative to allow any size. 
.TP
\fB--max-ips-per-target=\fISIZE\fB\f1
Maximum number of IPs per target. 
.TP
\fB-u, --update\f1
Updates the database with information from a running scanner (openvassd) and exits.
.TP
\fB-p, --port=\fINUMBER\fB\f1
Listen on port number \fINUMBER\f1.
.TP
\fB--rebuild\f1
Rebuild the database with information from a running scanner (openvassd) and exits.
.TP
\fB-s, --sport=\fINUMBER\fB\f1
Connect to server (openvassd) on port number \fINUMBER\f1.
.TP
\fB--version\f1
Print version.
.TP
\fB-v, --verbose\f1
Print progress messages.
.TP
\fB-?, --help\f1
Show help.
.SH SIGNALS
SIGHUP causes openvasmd to rebuild the database with information from the Scanner (openvassd).
.SH EXAMPLES
openvasmd --port 1241 --sport 7772

Serve OMP clients on port 1241 and connect to a OTP server on 7772.
.SH SEE ALSO
\fBopenvassd(8)\f1 \fBopenvasad(8)\f1 \fBgsad(8)\f1 \fBomp(8)\f1 \fBgsd(8)\f1
.SH MORE INFORMATION ABOUT THE OPENVAS PROJECT
The canonical places where you will find more information about the OpenVAS project are: \fBhttp://www.openvas.org/\f1 (Official site) \fBhttp://wald.intevation.org/projects/openvas/\f1 (Development Platform) 
.SH COPYRIGHT
The OpenVAS Manager is released under the GNU GPL, version 2, or, at your option, any later version. 
