#!/bin/sh
#
# OpenVAS
# $Id$
# Description: Escalator method script: SMB.
#
# Authors:
# Timo Pollmeier <timo.pollmeier@greenbone.net>
#
# Copyright:
# Copyright (C) 2016 Greenbone Networks GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

SHARE_LOCATION=$1        # \\host\share.
DEST_PATH=$2             # Path relative to the share
AUTH_PATH=$3             # Path to the authentication file
REPORT_PATH=$4           # Path to the report

smbclient -A "$AUTH_PATH" "$SHARE_LOCATION" -c "put \"$REPORT_PATH\" \"$DEST_PATH\"" >&2
EXIT_CODE=$?

exit $EXIT_CODE
