#!/bin/sh
# Copyright (C) 2011-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Escalator method script: Sourcefire connector.

greenbone_sourcefire_connector -server=$1 -port=$2 -pkcs12=$3 -password="$5" $4
EXIT_CODE=$?
exit $EXIT_CODE
