#!/bin/sh
# Copyright (C) 2016-2018 Greenbone Networks GmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Escalator method script: SNMP.

COMMUNITY=$1
AGENT=$2  # Host.
MESSAGE=$3

OUTPUT=$(snmptrap -v 2c -c $COMMUNITY $AGENT '' .1.3.6.1.6.3 0 s "$MESSAGE" 2>&1)

EXIT_CODE=$?

if [ "0" -ne "$EXIT_CODE" ]
then
  echo "snmptrap failed with code $EXIT_CODE:\n$OUTPUT" >&2
  exit $EXIT_CODE
fi
