#!/bin/sh
# Copyright (C) 2012-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Escalator method script: verinice connector.

greenbone_verinice_connector $1 $2 $3 $4
EXIT_CODE=$?
exit $EXIT_CODE
