#!/bin/sh
# Copyright (C) 2012-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Schema generator script: Brief XML.
#
# This schema generator creates a brief XML description of the protocol.
# Basically just the command list.

xsltproc ./GMP.xsl $1
