name: "Build Documentation"

on:
  push:
    branches: [main, stable, oldstable]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-doc-and-upload-coverage:
    name: Build XML documentation and upload coverage
    runs-on: ubuntu-latest
    container: greenbone/doxygen
    steps:
      - name: Run the c lang coverage action
        uses: greenbone/actions/doc-coverage-clang@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-gmp-doc:
    name: Build GMP documentation
    runs-on: ubuntu-latest
    container: ghcr.io/greenbone/gvm-libs:stable
    steps:
      - name: Check out gvmd
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Generate GMP documentation (HTML)
        run: |
          mkdir build
          cd build
          cmake -DSKIP_SRC=1 ..
          make doc-gmp
      - name: Upload GMP documentation artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gmp.html
          path: build/doc/gmp.html
          retention-days: 14
