name: Manually release gvmd with pontos

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"

jobs:
  build-and-release:
    name: Build and release with pontos
    runs-on: "ubuntu-latest"
    steps:
      - name: Release with release action
        uses: greenbone/actions/release@v2
        with:
          conventional-commits: true
          ref: ${{ github.event.inputs.branch }}
          github-user: ${{ secrets.GREENBONE_BOT }}
          github-user-mail: ${{ secrets.GREENBONE_BOT_MAIL }}
          github-user-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
