#!/bin/sh
#
# OpenVAS
# $Id$
# Description: Report generator script: NBE.
#
# This report generator creates the old Nessus NBE
# format for reports. The XML report is tranformed
# via a XSL script into the line-oriented CSV
# format called NBE.
#
# To run this generator properly, the tool xsltproc
# needs to be accesible.
#
# Authors:
# Matthew Mundell <matthew.mundell@greenbone.net>
#
# Copyright:
# Copyright (C) 2010 Greenbone Networks GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2,
# or, at your option, any later version as published by the Free
# Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

xsltproc ./NBE.xsl $1
